singleQuote: false
bracketSpacing: true
htmlWhitespaceSensitivity: "ignore"
singleAttributePerLine: true
proseWrap: "always"
plugins:
  - "prettier-plugin-go-template"
overrides:
  - files:
      - "*.html"
    options:
      parser: "go-template"
