baseurl = "//jasonwhite.us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[author]
  name = "Jason White"
  email = "jasonawhite@gmail.com"
languageCode = "en-us"
title = "Jason White"
[markup.goldmark.renderer]
unsafe= true
rssLimit = 20
