baseurl = "https://jasonwhite.us/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-us"
rssLimit = 20
title = 'Jason White'
buildDrafts = false

[params]
  author = "Jason White"
  description = "Personal site of Jason White, a photographer and developer based in Charlotte, North Carolina."

[permalinks]
	journal = "/journal/:year/:month/:day/:title/"
	links = "/:year/:month/:day/:title/"
	now = "/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"

# [[menus.main]]
# 	name = 'Home'
# 	pageRef = '/'
# 	weight = 10

[[menus.main]]
	name = 'Journal'
	pageRef = '/journal'
	weight = 20

[[menus.main]]
    name = 'Links'
    pageRef = '/links'
    weight = 30

[[menus.main]]
	name = 'Now'
	pageRef = '/now'
	weight = 40
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 50

[[menus.internal]]
  name = 'Uses'
  pageRef = '/uses'
  post = 'A list of all of the things I use from hardware to software, camera gear, and more.'
  weight = 10

# [[menus.internal]]
#   name = 'Blogroll'
#   pageRef = '/blogroll'
#   post = "The sites that I subscribe to and enjoy reading on a regular basis."
#   weight = 20

[[menus.internal]]
  name = 'Todo'
  pageRef = '/todo'
  post = "Things I need to take care of 'round these parts."
  weight = 30


[[menus.social]]
    name = 'Mastodon'
    url = 'https://mas.to/@nux'
    weight = 10

[[menus.social]]
    name = 'last.fm'
    url = 'https://www.last.fm/user/qbertqbert'
    weight = 20

[[menus.social]]
    name = 'Discogs'
    url = 'https://www.discogs.com/user/qbrt/collection?page=1&sort=artist%2Casc&folder=0&limit=25'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
    [markup.goldmark.extensions]
      attributes = true

[outputs]
  home = ["HTML", "RSS"]

[[mounts]]
  source = "assets"
  target = "assets"
